all_particles = {
    { path='data/entities/particles/berserk.xml',name='Berserk' },
    { path='data/entities/particles/blindness.xml',name='Blindness' },
    { path='data/entities/particles/blood_trail_small.xml',name='Blood trail small' },
    { path='data/entities/particles/charm.xml',name='Charm' },
    { path='data/entities/particles/critical_hit.xml',name='Critical hit' },
    { path='data/entities/particles/critical_hit_projectile.xml',name='Critical hit projectile' },
    { path='data/entities/particles/death.xml',name='Death' },
    { path='data/entities/particles/destruction.xml',name='Destruction' },
    { path='data/entities/particles/drunk.xml',name='Drunk' },
    { path='data/entities/particles/electricity.xml',name='Electricity' },
    { path='data/entities/particles/evaporation.xml',name='Evaporation' },
    { path='data/entities/particles/fog_of_war_hole.xml',name='Fog of war hole' },
    { path='data/entities/particles/freeze_charge.xml',name='Freeze charge' },
    { path='data/entities/particles/gas_bubble.xml',name='Gas bubble' },
    { path='data/entities/particles/gold_pickup.xml',name='Gold pickup' },
    { path='data/entities/particles/gold_pickup_particles.xml',name='Gold pickup particles' },
    { path='data/entities/particles/heal.xml',name='Heal' },
    { path='data/entities/particles/heart_out.xml',name='Heart out' },
    { path='data/entities/particles/heavy_shot.xml',name='Heavy shot' },
    { path='data/entities/particles/knockback.xml',name='Knockback' },
    { path='data/entities/particles/lantern_death.xml',name='Lantern death' },
    { path='data/entities/particles/lantern_small_death.xml',name='Lantern small death' },
    { path='data/entities/particles/levitation.xml',name='Levitation' },
    { path='data/entities/particles/particle_sparks.xml',name='Particle sparks' },
    { path='data/entities/particles/polymorph.xml',name='Polymorph' },
    { path='data/entities/particles/polymorph_explosion.xml',name='Polymorph explosion' },
    { path='data/entities/particles/spiral_shot_particle.xml',name='Spiral shot particle' },
    { path='data/entities/particles/telepathy.xml',name='Telepathy' },
    { path='data/entities/particles/teleportation.xml',name='Teleportation' },
    { path='data/entities/particles/teleportation_blast.xml',name='Teleportation blast' },
    { path='data/entities/particles/teleportation_source.xml',name='Teleportation source' },
    { path='data/entities/particles/teleportation_target.xml',name='Teleportation target' },
    { path='data/entities/particles/tinyspark_green.xml',name='Tinyspark green' },
    { path='data/entities/particles/tinyspark_orange.xml',name='Tinyspark orange' },
    { path='data/entities/particles/tinyspark_purple.xml',name='Tinyspark purple' },
    { path='data/entities/particles/tinyspark_purple_bright.xml',name='Tinyspark purple bright' },
    { path='data/entities/particles/tinyspark_red.xml',name='Tinyspark red' },
    { path='data/entities/particles/tinyspark_white.xml',name='Tinyspark white' },
    { path='data/entities/particles/tinyspark_yellow.xml',name='Tinyspark yellow' },
    { path='data/entities/particles/wand_pickup.xml',name='Wand pickup' },
    { path='data/entities/particles/water_electrocution.xml',name='Water electrocution' },
    { path='data/entities/particles/_example_expanding_polymorph_explosion.xml',name=' example expanding polymorph explosion' },
    { path='data/entities/particles/fireworks/firework_blue.xml',name='Firework blue' },
    { path='data/entities/particles/fireworks/firework_green.xml',name='Firework green' },
    { path='data/entities/particles/fireworks/firework_orange.xml',name='Firework orange' },
    { path='data/entities/particles/fireworks/firework_pink.xml',name='Firework pink' },
    { path='data/entities/particles/muzzle_flashes/muzzle_flash_air.xml',name='Muzzle flash air' },
    { path='data/entities/particles/muzzle_flashes/muzzle_flash_large.xml',name='Muzzle flash large' },
    { path='data/entities/particles/muzzle_flashes/muzzle_flash_large_pink.xml',name='Muzzle flash large pink' },
    { path='data/entities/particles/muzzle_flashes/muzzle_flash_laser.xml',name='Muzzle flash laser' },
    { path='data/entities/particles/muzzle_flashes/muzzle_flash_laser_green.xml',name='Muzzle flash laser green' },
    { path='data/entities/particles/muzzle_flashes/muzzle_flash_launcher.xml',name='Muzzle flash launcher' },
    { path='data/entities/particles/muzzle_flashes/muzzle_flash_launcher_large.xml',name='Muzzle flash launcher large' },
    { path='data/entities/particles/muzzle_flashes/muzzle_flash_magic_large.xml',name='Muzzle flash magic large' },
    { path='data/entities/particles/muzzle_flashes/muzzle_flash_magic_launcher.xml',name='Muzzle flash magic launcher' },
    { path='data/entities/particles/muzzle_flashes/muzzle_flash_magic_launcher_blue.xml',name='Muzzle flash magic launcher blue' },
    { path='data/entities/particles/muzzle_flashes/muzzle_flash_magic_launcher_holy.xml',name='Muzzle flash magic launcher holy' },
    { path='data/entities/particles/muzzle_flashes/muzzle_flash_magic_launcher_large.xml',name='Muzzle flash magic launcher large' },
    { path='data/entities/particles/muzzle_flashes/muzzle_flash_magic_launcher_large_blue.xml',name='Muzzle flash magic launcher large blue' },
    { path='data/entities/particles/muzzle_flashes/muzzle_flash_magic_launcher_trailer.xml',name='Muzzle flash magic launcher trailer' },
    { path='data/entities/particles/muzzle_flashes/muzzle_flash_magic_medium.xml',name='Muzzle flash magic medium' },
    { path='data/entities/particles/muzzle_flashes/muzzle_flash_magic_small.xml',name='Muzzle flash magic small' },
    { path='data/entities/particles/muzzle_flashes/muzzle_flash_medium.xml',name='Muzzle flash medium' },
    { path='data/entities/particles/muzzle_flashes/muzzle_flash_pink.xml',name='Muzzle flash pink' },
    { path='data/entities/particles/muzzle_flashes/muzzle_flash_small.xml',name='Muzzle flash small' },
    { path='data/entities/particles/muzzle_flashes/muzzle_flash_small_pink.xml',name='Muzzle flash small pink' },
    { path='data/entities/particles/image_emitters/acid_gas.xml',name='Acid gas' },
    { path='data/entities/particles/image_emitters/altar_tablet_curse_symbol.xml',name='Altar tablet curse symbol' },
    { path='data/entities/particles/image_emitters/chest_effect.xml',name='Chest effect' },
    { path='data/entities/particles/image_emitters/chest_effect_bad.xml',name='Chest effect bad' },
    { path='data/entities/particles/image_emitters/controls_a.xml',name='Controls a' },
    { path='data/entities/particles/image_emitters/controls_b.xml',name='Controls b' },
    { path='data/entities/particles/image_emitters/controls_back.xml',name='Controls back' },
    { path='data/entities/particles/image_emitters/controls_f.xml',name='Controls f' },
    { path='data/entities/particles/image_emitters/controls_i.xml',name='Controls i' },
    { path='data/entities/particles/image_emitters/controls_inventory.xml',name='Controls inventory' },
    { path='data/entities/particles/image_emitters/controls_inventory_gamepad.xml',name='Controls inventory gamepad' },
    { path='data/entities/particles/image_emitters/controls_lt.xml',name='Controls lt' },
    { path='data/entities/particles/image_emitters/controls_mouse.xml',name='Controls mouse' },
    { path='data/entities/particles/image_emitters/controls_stick.xml',name='Controls stick' },
    { path='data/entities/particles/image_emitters/controls_stickpress.xml',name='Controls stickpress' },
    { path='data/entities/particles/image_emitters/controls_wasd.xml',name='Controls wasd' },
    { path='data/entities/particles/image_emitters/heart_effect.xml',name='Heart effect' },
    { path='data/entities/particles/image_emitters/heart_fullhp_effect.xml',name='Heart fullhp effect' },
    { path='data/entities/particles/image_emitters/image_explosion.xml',name='Image explosion' },
    { path='data/entities/particles/image_emitters/magical_symbol.xml',name='Magical symbol' },
    { path='data/entities/particles/image_emitters/magical_symbol_fast.xml',name='Magical symbol fast' },
    { path='data/entities/particles/image_emitters/orbroom.xml',name='Orbroom' },
    { path='data/entities/particles/image_emitters/orb_effect.xml',name='Orb effect' },
    { path='data/entities/particles/image_emitters/perk_effect.xml',name='Perk effect' },
    { path='data/entities/particles/image_emitters/perk_effect_pacifist.xml',name='Perk effect pacifist' },
    { path='data/entities/particles/image_emitters/player_disappear_effect_left.xml',name='Player disappear effect left' },
    { path='data/entities/particles/image_emitters/player_disappear_effect_right.xml',name='Player disappear effect right' },
    { path='data/entities/particles/image_emitters/potion_effect.xml',name='Potion effect' },
    { path='data/entities/particles/image_emitters/shop_effect.xml',name='Shop effect' },
    { path='data/entities/particles/image_emitters/spell_refresh_effect.xml',name='Spell refresh effect' },
    { path='data/entities/particles/image_emitters/transmutation_effect.xml',name='Transmutation effect' },
    { path='data/entities/particles/image_emitters/wand_effect.xml',name='Wand effect' },
    { path='data/entities/particles/particle_explosion/base_smoke_trail.xml',name='Base smoke trail' },
    { path='data/entities/particles/particle_explosion/base_spark_trail.xml',name='Base spark trail' },
    { path='data/entities/particles/particle_explosion/explosion_flare.xml',name='Explosion flare' },
    { path='data/entities/particles/particle_explosion/explosion_flare_blue.xml',name='Explosion flare blue' },
    { path='data/entities/particles/particle_explosion/explosion_flare_blue_small.xml',name='Explosion flare blue small' },
    { path='data/entities/particles/particle_explosion/explosion_flare_fog_of_war_hole.xml',name='Explosion flare fog of war hole' },
    { path='data/entities/particles/particle_explosion/explosion_flare_fog_of_war_hole_medium.xml',name='Explosion flare fog of war hole medium' },
    { path='data/entities/particles/particle_explosion/explosion_flare_fog_of_war_hole_small.xml',name='Explosion flare fog of war hole small' },
    { path='data/entities/particles/particle_explosion/explosion_flare_medium.xml',name='Explosion flare medium' },
    { path='data/entities/particles/particle_explosion/explosion_flare_small.xml',name='Explosion flare small' },
    { path='data/entities/particles/particle_explosion/explosion_smoke_pillar.xml',name='Explosion smoke pillar' },
    { path='data/entities/particles/particle_explosion/explosion_smoke_pillar_green.xml',name='Explosion smoke pillar green' },
    { path='data/entities/particles/particle_explosion/explosion_smoke_pillar_green_large.xml',name='Explosion smoke pillar green large' },
    { path='data/entities/particles/particle_explosion/explosion_smoke_pillar_grey.xml',name='Explosion smoke pillar grey' },
    { path='data/entities/particles/particle_explosion/explosion_smoke_pillar_large.xml',name='Explosion smoke pillar large' },
    { path='data/entities/particles/particle_explosion/explosion_smoke_pillar_pink.xml',name='Explosion smoke pillar pink' },
    { path='data/entities/particles/particle_explosion/explosion_smoke_pillar_top_left.xml',name='Explosion smoke pillar top left' },
    { path='data/entities/particles/particle_explosion/explosion_smoke_pillar_top_left_green.xml',name='Explosion smoke pillar top left green' },
    { path='data/entities/particles/particle_explosion/explosion_smoke_pillar_top_left_grey.xml',name='Explosion smoke pillar top left grey' },
    { path='data/entities/particles/particle_explosion/explosion_smoke_pillar_top_left_pink.xml',name='Explosion smoke pillar top left pink' },
    { path='data/entities/particles/particle_explosion/explosion_smoke_pillar_top_right.xml',name='Explosion smoke pillar top right' },
    { path='data/entities/particles/particle_explosion/explosion_smoke_pillar_top_right_green.xml',name='Explosion smoke pillar top right green' },
    { path='data/entities/particles/particle_explosion/explosion_smoke_pillar_top_right_grey.xml',name='Explosion smoke pillar top right grey' },
    { path='data/entities/particles/particle_explosion/explosion_smoke_pillar_top_right_pink.xml',name='Explosion smoke pillar top right pink' },
    { path='data/entities/particles/particle_explosion/explosion_trail_smoke.xml',name='Explosion trail smoke' },
    { path='data/entities/particles/particle_explosion/explosion_trail_smoke_green.xml',name='Explosion trail smoke green' },
    { path='data/entities/particles/particle_explosion/explosion_trail_smoke_green_large.xml',name='Explosion trail smoke green large' },
    { path='data/entities/particles/particle_explosion/explosion_trail_smoke_grey.xml',name='Explosion trail smoke grey' },
    { path='data/entities/particles/particle_explosion/explosion_trail_smoke_grey_short.xml',name='Explosion trail smoke grey short' },
    { path='data/entities/particles/particle_explosion/explosion_trail_smoke_large.xml',name='Explosion trail smoke large' },
    { path='data/entities/particles/particle_explosion/explosion_trail_smoke_nospark.xml',name='Explosion trail smoke nospark' },
    { path='data/entities/particles/particle_explosion/explosion_trail_smoke_pink.xml',name='Explosion trail smoke pink' },
    { path='data/entities/particles/particle_explosion/explosion_trail_smoke_short.xml',name='Explosion trail smoke short' },
    { path='data/entities/particles/particle_explosion/explosion_trail_spark.xml',name='Explosion trail spark' },
    { path='data/entities/particles/particle_explosion/explosion_trail_spark_blue.xml',name='Explosion trail spark blue' },
    { path='data/entities/particles/particle_explosion/explosion_trail_spark_blue_small.xml',name='Explosion trail spark blue small' },
    { path='data/entities/particles/particle_explosion/explosion_trail_spark_large.xml',name='Explosion trail spark large' },
    { path='data/entities/particles/particle_explosion/explosion_trail_spark_pink.xml',name='Explosion trail spark pink' },
    { path='data/entities/particles/particle_explosion/explosion_trail_spark_short.xml',name='Explosion trail spark short' },
    { path='data/entities/particles/particle_explosion/explosion_trail_spark_small.xml',name='Explosion trail spark small' },
    { path='data/entities/particles/particle_explosion/main.xml',name='Main' },
    { path='data/entities/particles/particle_explosion/main_blue.xml',name='Main blue' },
    { path='data/entities/particles/particle_explosion/main_bluesmoke.xml',name='Main bluesmoke' },
    { path='data/entities/particles/particle_explosion/main_bluesmoke_small.xml',name='Main bluesmoke small' },
    { path='data/entities/particles/particle_explosion/main_contained.xml',name='Main contained' },
    { path='data/entities/particles/particle_explosion/main_green.xml',name='Main green' },
    { path='data/entities/particles/particle_explosion/main_green_large.xml',name='Main green large' },
    { path='data/entities/particles/particle_explosion/main_green_small.xml',name='Main green small' },
    { path='data/entities/particles/particle_explosion/main_large.xml',name='Main large' },
    { path='data/entities/particles/particle_explosion/main_large_radius.xml',name='Main large radius' },
    { path='data/entities/particles/particle_explosion/main_medium.xml',name='Main medium' },
    { path='data/entities/particles/particle_explosion/main_nospark.xml',name='Main nospark' },
    { path='data/entities/particles/particle_explosion/main_pink.xml',name='Main pink' },
    { path='data/entities/particles/particle_explosion/main_small.xml',name='Main small' },
    { path='data/entities/particles/bounce_effects/bouncy_orb.xml',name='Bouncy orb' },
    { path='data/entities/particles/bounce_effects/rubber_ball.xml',name='Rubber ball' },
    { path='data/entities/particles/bounce_effects/spitter.xml',name='Spitter' },
    { path='data/entities/particles/bounce_effects/spitter_green.xml',name='Spitter green' },
    { path='data/entities/particles/bounce_effects/spitter_purple.xml',name='Spitter purple' },
}