all_particles = {
    {path='data/entities/particles/berserk.xml',name='Berserk'},
    {path='data/entities/particles/blindness.xml',name='Blindness'},
    {path='data/entities/particles/blood_trail_small.xml',name='Blood trail small'},
    {path='data/entities/particles/charm.xml',name='Charm'},
    {path='data/entities/particles/charm_oneoff.xml',name='Charm oneoff'},
    {path='data/entities/particles/critical_hit.xml',name='Critical hit'},
    {path='data/entities/particles/critical_hit_projectile.xml',name='Critical hit projectile'},
    {path='data/entities/particles/death.xml',name='Death'},
    {path='data/entities/particles/destruction.xml',name='Destruction'},
    {path='data/entities/particles/drunk.xml',name='Drunk'},
    {path='data/entities/particles/electricity.xml',name='Electricity'},
    {path='data/entities/particles/evaporation.xml',name='Evaporation'},
    {path='data/entities/particles/fog_of_war_hole.xml',name='Fog of war hole'},
    {path='data/entities/particles/freeze_charge.xml',name='Freeze charge'},
    {path='data/entities/particles/gas_bubble.xml',name='Gas bubble'},
    {path='data/entities/particles/gold_pickup.xml',name='Gold pickup'},
    {path='data/entities/particles/gold_pickup_huge.xml',name='Gold pickup huge'},
    {path='data/entities/particles/gold_pickup_large.xml',name='Gold pickup large'},
    {path='data/entities/particles/gold_pickup_particles.xml',name='Gold pickup particles'},
    {path='data/entities/particles/heal.xml',name='Heal'},
    {path='data/entities/particles/heart_out.xml',name='Heart out'},
    {path='data/entities/particles/heavy_shot.xml',name='Heavy shot'},
    {path='data/entities/particles/knockback.xml',name='Knockback'},
    {path='data/entities/particles/lantern_death.xml',name='Lantern death'},
    {path='data/entities/particles/lantern_small_death.xml',name='Lantern small death'},
    {path='data/entities/particles/levitation.xml',name='Levitation'},
    {path='data/entities/particles/light_shot.xml',name='Light shot'},
    {path='data/entities/particles/particle_sparks.xml',name='Particle sparks'},
    {path='data/entities/particles/perk_reroll.xml',name='Perk reroll'},
    {path='data/entities/particles/polymorph.xml',name='Polymorph'},
    {path='data/entities/particles/polymorph_explosion.xml',name='Polymorph explosion'},
    {path='data/entities/particles/poof_pink.xml',name='Poof pink'},
    {path='data/entities/particles/spiral_shot_particle.xml',name='Spiral shot particle'},
    {path='data/entities/particles/telepathy.xml',name='Telepathy'},
    {path='data/entities/particles/teleportation.xml',name='Teleportation'},
    {path='data/entities/particles/teleportation_blast.xml',name='Teleportation blast'},
    {path='data/entities/particles/teleportation_source.xml',name='Teleportation source'},
    {path='data/entities/particles/teleportation_target.xml',name='Teleportation target'},
    {path='data/entities/particles/tinyspark_green.xml',name='Tinyspark green'},
    {path='data/entities/particles/tinyspark_orange.xml',name='Tinyspark orange'},
    {path='data/entities/particles/tinyspark_purple.xml',name='Tinyspark purple'},
    {path='data/entities/particles/tinyspark_purple_bright.xml',name='Tinyspark purple bright'},
    {path='data/entities/particles/tinyspark_red.xml',name='Tinyspark red'},
    {path='data/entities/particles/tinyspark_white.xml',name='Tinyspark white'},
    {path='data/entities/particles/tinyspark_yellow.xml',name='Tinyspark yellow'},
    {path='data/entities/particles/tiny_ghost_poof.xml',name='Tiny ghost poof'},
    {path='data/entities/particles/treble_eye.xml',name='Treble eye'},
    {path='data/entities/particles/vomit.xml',name='Vomit'},
    {path='data/entities/particles/wand_pickup.xml',name='Wand pickup'},
    {path='data/entities/particles/water_electrocution.xml',name='Water electrocution'},
    {path='data/entities/particles/_example_expanding_polymorph_explosion.xml',name=' example expanding polymorph explosion'}
}