pickupable = {
    {path='data/entities/items/pickup/cape.xml',name='Cape'},
    {path='data/entities/items/pickup/chest_random.xml',name='Chest random'},
    {path='data/entities/items/pickup/chest_random_super.xml',name='Chest random super'},
    {path='data/entities/items/pickup/egg_fire.xml',name='Egg fire'},
    {path='data/entities/items/pickup/egg_hollow.xml',name='Egg hollow'},
    {path='data/entities/items/pickup/egg_monster.xml',name='Egg monster'},
    {path='data/entities/items/pickup/egg_red.xml',name='Egg red'},
    {path='data/entities/items/pickup/egg_slime.xml',name='Egg slime'},
    {path='data/entities/items/pickup/egg_worm.xml',name='Egg worm'},
    {path='data/entities/items/pickup/essence_air.xml',name='Essence air'},
    {path='data/entities/items/pickup/essence_alcohol.xml',name='Essence alcohol'},
    {path='data/entities/items/pickup/essence_fire.xml',name='Essence fire'},
    {path='data/entities/items/pickup/essence_laser.xml',name='Essence laser'},
    {path='data/entities/items/pickup/essence_water.xml',name='Essence water'},
    {path='data/entities/items/pickup/goldnugget.xml',name='Goldnugget'},
    {path='data/entities/items/pickup/goldnugget_10.xml',name='Goldnugget 10'},
    {path='data/entities/items/pickup/goldnugget_1000.xml',name='Goldnugget 1000'},
    {path='data/entities/items/pickup/goldnugget_10000.xml',name='Goldnugget 10000'},
    {path='data/entities/items/pickup/goldnugget_200.xml',name='Goldnugget 200'},
    {path='data/entities/items/pickup/goldnugget_50.xml',name='Goldnugget 50'},
    {path='data/entities/items/pickup/heart.xml',name='Heart'},
    {path='data/entities/items/pickup/heart_better.xml',name='Heart better'},
    {path='data/entities/items/pickup/heart_evil.xml',name='Heart evil'},
    {path='data/entities/items/pickup/heart_fullhp.xml',name='Heart fullhp'},
    {path='data/entities/items/pickup/heart_fullhp_temple.xml',name='Heart fullhp temple'},
    {path='data/entities/items/pickup/perk.xml',name='Perk'},
    {path='data/entities/items/pickup/perk_reroll.xml',name='Perk reroll'},
    {path='data/entities/items/pickup/potion.xml',name='Potion'},
    {path='data/entities/items/pickup/potion_aggressive.xml',name='Potion aggressive'},
    {path='data/entities/items/pickup/potion_random_material.xml',name='Potion random material'},
    {path='data/entities/items/pickup/potion_secret.xml',name='Potion secret'},
    {path='data/entities/items/pickup/potion_water.xml',name='Potion water'},
    {path='data/entities/items/pickup/random_card.xml',name='Random card'},
    {path='data/entities/items/pickup/spell_refresh.xml',name='Spell refresh'},
    {path='data/entities/items/pickup/thunderstone.xml',name='Thunderstone'},
}